name: Run Node.js Server on AWS EC2

on:
  push:
    branches: [main]

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Run server on EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            cd docker-ci/ &&
            git pull origin main &&
            cd src/ &&
            nohup node index.js > output.log 2>&1 &
            echo "Server started successfully"
          '

      - name: Mark job as complete
        run: echo "Server is running. Job complete!"
