name: Docker CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Run Docker image and perform health check
        run: |
          container_id=$(docker run -d myapp:latest)
          echo "Container started with ID: $container_id"

          # Wait for the container to start up (adjust sleep time as needed)
          sleep 10

          # Perform a health check (adjust as needed for your app)
          if docker exec $container_id node -e "console.log('Health check passed')"; then
            echo "Health check passed"
          else
            echo "Health check failed"
            exit 1
          fi

          # Stop and remove the container
          docker stop $container_id
          docker rm $container_id

      - name: Cleanup
        if: always()
        run: |
          docker image rm myapp:latest || true
